import vm from 'node:vm';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const storage=new Map();let failStorage=false;
const elements=new Map();
function element(selector){if(!elements.has(selector))elements.set(selector,{innerHTML:'',textContent:'',value:'',disabled:false,classList:{add(){},remove(){}},addEventListener(){},showModal(){this.open=true},close(){this.open=false},focus(){},setAttribute(){},querySelector(){return element('child')},setSelectionRange(){}});return elements.get(selector)}
const context=vm.createContext({console,URL,URLSearchParams,Blob,crypto:webcrypto,structuredClone,setTimeout(){return 0},clearTimeout(){},navigator:{},location:{hash:'#/',origin:'http://localhost:3000'},sessionStorage:{getItem(){return null},setItem(){},removeItem(){}},localStorage:{getItem:k=>storage.get(k)??null,setItem(k,v){if(failStorage)throw Error('quota');storage.set(k,v)},removeItem:k=>storage.delete(k)},document:{querySelector:element,querySelectorAll:()=>[],addEventListener(){},createElement:()=>element('anchor')},window:{location:{origin:'http://localhost:3000'},addEventListener(){},scrollTo(){}},Image:class{naturalWidth=100;naturalHeight=100;set src(v){this.onload?.()}}});
const run=code=>vm.runInContext(code,context);
for(const file of ['dist/vendor/xlsx.full.min.js','dist/app.js','dist/operations.js'])run(fs.readFileSync(path.join(root,file),'utf8'));
run("user={role:'customer',email:'customer@powerelectronics.demo'}");
const bytes=fs.readFileSync(path.join(root,'dist/samples/power-electronics-bulk-order.xlsx'));context.uploadBytes=new Uint8Array(bytes);
run("const bulkWorkbook=XLSX.read(uploadBytes,{type:'array'});bulkDraft={items:normalizeBulkRows(sheetMatrix(bulkWorkbook,'Items')),filename:'sample.xlsx'}");
assert.equal(run('bulkDraft.items.reduce((a,i)=>a+i.count,0)'),165);
run("submitBulkRequest({name:'Demo Customer',email:'customer@example.com',phone:'9876543210',institution:'Demo College',institutionType:'College',notes:'Lab project'})");
assert.equal(run('bulkOrders[0].status'),'Submitted');
assert.match(run('customerBulkPage()'),/Demo College/);
assert.throws(()=>run("updateBulkOrder(bulkOrders[0].id,{status:'Quoted',quote:'25000',adminNotes:''})"),/administrator/);
run("user={role:'admin',email:'admin@powerelectronics.demo'}");
assert.throws(()=>run("updateBulkOrder(bulkOrders[0].id,{status:'Completed',quote:'25000',adminNotes:''})"),/one stage/);
for(const status of ['Quoted','Delivered','Completed'])run(`updateBulkOrder(bulkOrders[0].id,{status:'${status}',quote:'25000',adminNotes:'Reviewed'})`);
assert.equal(run('bulkOrders[0].history.length'),4);
assert.throws(()=>run("updateBulkOrder(bulkOrders[0].id,{status:'Completed',quote:'25001',adminNotes:'Reviewed'})"),/closed/);
run("pricingPreview=calculatePricePreview({scope:'all',type:'percent',direction:'increase',amount:'0.5',reason:'Supplier revision'})");
assert.equal(run('pricingPreview.rows[0].after'),551.75);
run('commitProductChanges(pricingPreview.rows.map(r=>({id:r.id,price:r.after})),pricingPreview.reason)');
assert.equal(run('priceHistory.length'),14);
run("pricingCategory='Sensors';pricingPreview=calculatePricePreview({scope:'category',type:'fixed',direction:'increase',amount:'25',reason:'Category adjustment'})");
assert.equal(run('pricingPreview.rows.length'),3);
run('commitProductChanges(pricingPreview.rows.map(r=>({id:r.id,price:r.after})),pricingPreview.reason)');
assert.equal(run('product(6).price'),74.25);assert.equal(run('product(1).price'),551.75);
run("cart=[{id:6,qty:2}];commitProductChanges([{id:6,stock:0}],'Out of stock')");
assert.equal(run('cart.length'),0);assert.match(run('cardCartControl(product(6))'),/disabled/);
run("commitProductChanges([{id:6,price:79,old:99}],'Individual product edit')");
assert.equal(run('priceHistory[0].reason'),'Individual product edit');
const before=run('JSON.stringify({products,priceHistory})');failStorage=true;assert.throws(()=>run("commitProductChanges([{id:1,price:600}],'Storage failure')"),/not saved/);failStorage=false;assert.equal(run('JSON.stringify({products,priceHistory})'),before);
for(const matrix of [[['Item','Count'],['x',0]],[['Item','Count'],['x',1.5]],[['Item','Count'],['x',1],['X',2]],[['Item'],['x']]])assert.throws(()=>run(`normalizeBulkRows(${JSON.stringify(matrix)})`));
assert.throws(()=>run("calculatePricePreview({scope:'all',type:'percent',direction:'decrease',amount:'100',reason:'Invalid'})"),/outside/);
const productBytes=fs.readFileSync(path.join(root,'dist/samples/power-electronics-products.xlsx'));context.productBytes=new Uint8Array(productBytes);
run("catalogWorkbook=XLSX.read(productBytes,{type:'array'});catalogSheet='Products';catalogFilename='sample-products.xlsx';resetCatalogMap();validateCatalogPreview()");
assert.equal(run('catalogPreview.drafts.length'),6);assert.equal(run('catalogPreview.drafts[0].old'),'699');
await run('stageImport(catalogPreview.matrix,catalogFilename)');
assert.equal(run('importDrafts.length'),6);assert.equal(run("importDrafts.filter(d=>draftState(d)==='ready').length"),6);
run('publishImportProducts(importDrafts.map(d=>d.id))');assert.equal(run('products.length'),20);
run("importDrafts[0].price='599';importDrafts[0].status='draft';publishImportProducts([importDrafts[0].id])");assert.equal(run('products.length'),20);assert.equal(run('priceHistory[0].reason'),'Excel publication');
assert.equal(JSON.parse(storage.get('circuit-demo-price-history'))[0].after,599);
assert.equal(JSON.parse(storage.get('circuit-demo-bulk-orders'))[0].status,'Completed');
run("user={role:'customer',email:'customer@powerelectronics.demo'}");assert.throws(()=>run("commitProductChanges([{id:1,price:1}],'Unauthorized')"),/administrator/);
assert.match(run('customerBulkPage()'),/Completed/);
console.log('PASS: actual XLSX templates; bulk submission and status progression; percentage and category price adjustments; stock and cart sync; individual and Excel price history; rollback; authorization; invalid inputs; persistence.');
